# Configuration for the official Traefik Helm chart
traefik:
  # Deploy Traefik in its own namespace
  namespaceOverride: traefik

  # Service configuration
  service:
    type: LoadBalancer

  # Enable Kubernetes Ingress provider
  providers:
    kubernetesIngress:
      enabled: true
